export const GET_PRODUCTS = "GET_PRODUCTS"
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL"

export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT"
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS" 
export const GET_SINGLE_PRODUCT_FAIL = "GET_SINGLE_PRODUCT_FAIL"

export const WISHLIST = "WISHLIST"
export const UPDATE_WISHLIST_SUCCESS = "UPDATE_WISHLIST_SUCCESS"
export const UPDATE_WISHLIST_FAIL = "UPDATE_WISHLIST_FAIL"


